---

- name: Check if serviio is already installed
  stat:
    path: "{{ serviio_install_path }}/serviio-{{ serviio_version }}"
  register: is_installed

- name: Create group {{ serviio_group }}
  group:
    name: "{{ serviio_group }}"
    state: present

- name: Create user {{ serviio_user }}
  user:
    name: "{{ serviio_user }}"
    groups: "{{ serviio_group }}"
    state: present

- name: Download and unarchive serviio-{{ serviio_version }}-linux.tar.gz at {{ serviio_install_path }}
  unarchive:
    src: "{{ serviio_download_URL }}/serviio-{{ serviio_version }}-linux.tar.gz"
    dest: "{{ serviio_install_path }}"
    copy: no
    creates: "{{ serviio_install_path }}/serviio-{{ serviio_version }}"
    mode: o=r
    owner: "{{ serviio_user }}"
    group: "{{ serviio_group }}"
  register: installed
  when: is_installed.stat.exists == False

- name: Ensure perimissions on {{ serviio_install_path }}/serviio-{{ serviio_version }}
  file:
    path: "{{ serviio_install_path }}/serviio-{{ serviio_version }}"
    mode: o=r
    owner: "{{ serviio_user }}"
    group: "{{ serviio_group }}"
    state: "directory"
    recurse: yes
  changed_when: false
  when: is_installed.stat.exists or installed|changed
