---

- name: Install prerequisites (RedHat OS Family)
  include: install-prerequisites-EL.yml
  when: ansible_os_family == "RedHat"

- name: Install prerequisites (Ubuntu)
  include: install-prerequisites-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install serviio
  include: install-serviio.yml

- name: Configure service
  include: configure-service.yml
  when: serviio_create_service

- name: Configure firewalld
  include: configure-firewalld.yml
  when: serviio_configure_firewalld and ansible_os_family == "RedHat"
