---

- name: Install prerequisites
  include: install-prerequisites.yml
  when: ansible_os_family == "RedHat"

- name: Install serviio
  include: install-serviio.yml

- name: Configure service
  include: configure-service.yml
  when: serviio_create_service

- name: Configure firewalld
  include: configure-firewalld.yml
  when: serviio_configure_firewalld
